name: Verificacion Java

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Habilitar Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar y ejecutar pruebas
        run: ./mvnw --batch-mode clean verify
        
      - name: Compilar y ejecutar pruebas
        run: ./mvnw --batch-mode --no-transfer-progress clean verify
